version: "3.8"

services:
  db:
    image: mysql:8
    container_name: monbudget-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d

  adminer:
      image: adminer:latest
      container_name: monbudget-adminer
      ports:
        - "8080:8080"

volumes:
  db_data: